-- phpMyAdmin SQL Dump
-- version 4.8.4
-- https://www.phpmyadmin.net/
--
-- Host: mysql
-- Generation Time: Jul 18, 2019 at 02:48 PM
-- Server version: 10.3.13-MariaDB-1:10.3.13+maria~bionic
-- PHP Version: 7.2.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `Manga_DB`
--

-- --------------------------------------------------------

--
-- Table structure for table `Fan_Art`
--

CREATE TABLE `Fan_Art` (
  `id` int(11) NOT NULL,
  `nom_fan_art` varchar(1000) NOT NULL,
  `nom_createur` varchar(1000) NOT NULL,
  `URL` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `Fan_Art`
--

INSERT INTO `Fan_Art` (`id`, `nom_fan_art`, `nom_createur`, `URL`) VALUES
(1, 'dessin 1', 'tutu', '../image/background00.jpg'),
(2, 'dessin 2', 'toto', '../image/ass_classroom.png'),
(3, 'dessin 3', 'tata', '../image/charlotte.jpg'),
(4, 'dessin 4', 'titi', '../image/death_note1.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `manga`
--

CREATE TABLE `manga` (
  `id` int(11) NOT NULL,
  `nom` varchar(30) NOT NULL,
  `age` int(11) NOT NULL,
  `genre` varchar(1000) NOT NULL,
  `image` varchar(1000) NOT NULL,
  `description` text NOT NULL,
  `auteur` varchar(100) NOT NULL,
  `URL` varchar(1000) NOT NULL,
  `tome` int(11) NOT NULL,
  `episode` int(11) NOT NULL,
  `image1` varchar(1000) NOT NULL,
  `image2` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `manga`
--

INSERT INTO `manga` (`id`, `nom`, `age`, `genre`, `image`, `description`, `auteur`, `URL`, `tome`, `episode`, `image1`, `image2`) VALUES
(1, 'Evangelion', 16, 'Science-fiction, Suspense, Psychologie, Dramatique', '../image/evangelion.jpg', 'En l’an 2000, une gigantesque explosion se produisit en Antarctique, provoquant un cataclysme qui dévasta une grande partie de la planète. Les autorités déclarèrent que cette catastrophe était due à la chute d’un astéroïde.<br> Quinze ans plus tard, l’humanité a surmonté cet événement, appelé le Second Impact.<br> Mais de mystérieuses créatures géantes nommées Anges font leur apparition, et tentent de détruire Tokyo-3, la nouvelle capitale-forteresse du Japon, construite après le Second Impact. Pour les combattre, l’organisation secrète NERV<br> a mis au point une arme ultime, l’« Evangelion » ou « Eva », géant anthropoïde dont le pilotage repose sur la capacité du pilote à fusionner avec son mécha.<br><br>\r\n                                Shinji Ikari, quatorze ans, se rend à Tokyo-3 sur invitation de son père, directeur du projet Eva. Il est loin de se douter que sur ses épaules fragiles vont reposer le destin du monde et la fin de l’humanité… À moins qu’il ne s’agisse que du début d’une autre ère,annoncée depuis la nuit des temps par les manuscrits de la Mer Morte.', 'SADAMOTO Yoshiyuki', 'https://www.youtube.com/embed/13nSISwxrY4', 14, 26, '../image/evangelion1.jpg', '../image/evangelion2.jpg'),
(2, ' Made in Abyss', 16, 'Aventure , Fantasy sombre , Science-fiction\r\n', '../image/made_in_abyss.png', 'À la surface de cette planète, un seul endroit demeure encore mystérieux et inexploré : un trou gigantesque surnommé <br>« L\'Abysse ». Dans cette crevasse sans fond dorment des trésors que l\'humanité ne semble plus pouvoir reproduire. La fascination et l\'émerveillement que représente L\'Abysse poussent de nombreuses personnes à s\'y aventurer.<br><br>\r\n\r\n                                    Au pied de la ville d’Orse s’étend l’Abysse, une faille gigantesque à la profondeur inconnue habitée par d’étranges créatures et emplie d’antiques reliques. Depuis des années, ce mystérieux gouffre attire de nombreux aventuriers qui se font appeler <br>« les caverniers ». C’est ici que vit Rico, une jeune orpheline obsédée par l’Abysse et désirant marcher dans les traces de sa mère qui y a disparu. Un jour, en prospectant, Rico découvre le corps inanimé d’un jeune garçon. Elle est alors loin d’imaginer à quel point cette découverte va changer sa vie et accélérer son destin.', 'AKIHITO Tsukushi ', 'https://www.youtube.com/embed/e91G8m9uM_0', 5, 13, '../image/made_in_abyss1.jpg', '../image/made_in_abyss2.jpg'),
(3, 'Death Note', 16, 'Drame, Fantastique, Mystère, Psychologique, Surnaturel, Thriller', '../image/death_note.png', 'Light Yagami est un lycéen surdoué qui juge le monde actuel criminel, pourri et corrompu.<br> Sa vie change du tout au tout le jour où il ramasse par hasard un mystérieux cahier intitulé « Death Note ».<br> Son mode d\'emploi indique que « la personne dont le nom est écrit dans ce cahier meurt »', 'TSUGUMI Ohba', 'https://www.youtube.com/embed/l9mxA1OygXk', 13, 37, '../image/death_note1.jpg', '../image/death_note2.jpg'),
(4, 'Bleach', 12, 'Action, Aventure, Fantasy, Combat', '../image/bleach.jpg', 'Ichigo Kurosaki, un adolescent de quinze ans qui vient de rentrer au lycée. Sa particularité, outre le fait<br> d\'avoir des cheveux orange et d\'avoir un goût très prononcé pour la bagarre hérité visiblement de son père, est qu\'il <br>peut voir et toucher les morts. Régulièrement, Ichigo rencontre donc des fantômes auxquels il essaie de rendre service.<br>\r\n                                    Un soir, une Shinigami (terme désignant un être spirituel et pouvant être traduit par « dieu de la mort ») rentre dans sa chambre...', 'TITE Kubo', 'https://www.youtube.com/embed/N5gTn6hzMUo', 74, 366, '../image/bleach1.png', '../image/bleach2.jpg'),
(5, 'Psycho Pass', 16, 'Action, Drame, Psychologique, Science-fiction, Thriller', '../image/psycho_pass.png', 'Au début de l\'année 2112, il est possible de mesurer instantanément l\'état mental d\'une personne, sa personnalité et la probabilité qu\'elle commette des crimes grâce à un dispositif installé sur le corps de chaque citoyen appelé « Psycho-Pass ». Ce système est appelé « Sybil », et est mis en place par le Ministère du Bien-être ; accompagné d\'une auto-suffisance alimentaire, d\'un contrôle des arts, d\'un isolationnisme complet et de travaux pour rallonger la vie humaine (notamment par le biais d\'organes artificiels), Sybil a transformé la société en « monde parfait ». La quasi-totalité des mesures de prévention de la criminalité sont électroniques : scanneurs ou drones de surveillance mesurent en permanence l\'état de chacun.<br><br>\r\n\r\n                                Lorsque le Psycho-Pass, mesurée par le niveau du « coefficient de criminalité », est trop élevée chez certaines personnes, ces individus sont poursuivis et appréhendés afin de suivre une thérapie visant à réduire leur potentiel criminel. Mais s\'ils refusent où qu\'ils sont jugés inaptes à la réhabilitation, ils sont enfermés ou abattus. Cette tâche est effectuée par des équipes spéciales de criminels potentiels appelés Exécuteurs, qui sont supervisés par des policiers appelés Inspecteurs. Ces derniers n\'ont pas le droit de sortir du Bureau de la Sécurité Publique (BSP) au Japon sans un Inspecteur ; ils n\'ont pas non plus le droit de faire l\'usage de leurs armes sans l\'accord d\'un Inspecteur. Les Inspecteurs et Exécuteurs, peu nombreux (trois unités), utilisent une arme spéciale polymorphe appelée « Dominateur », conçue pour tirer uniquement sur ceux ayant un coefficient de criminalité plus élevé que la normale. Les Inspecteurs s\'assurent que les Exécuteurs exercent leurs fonctions dans les limites qui leur sont imposées ; dans le cas contraire, ils ont le droit de neutraliser leurs subordonnés, les Exécuteurs étant des criminels potentiels sont des cibles « ouvertes » pour les Dominateurs. L\'histoire suit l\'unité 1 de la division des enquêtes criminelles du BSP, lorsque Akane Tsunemori, toute jeune recrue, y prend ses fonctions.', 'UROBUCHI Gen', 'https://www.youtube.com/embed/YanxDoJBNEE', 6, 22, '../image/psycho_pass1.jpg', '../image/psycho_pass2.jpg'),
(6, 'Naruto', 10, 'Action, Aventure, Comédie, Drame, Fantasy, Combat', '../image/naruto.png', 'Dans le village de Konoha vit Naruto, un jeune garçon détesté et craint des villageois. Il est craint du fait qu\'il<br> détient en lui Kyuubi (démon renard à neuf queues) d\'une incroyable force, qui a tué un grand nombre de personnes. <br>Le ninja le plus puissant de Konoha à l\'époque, le quatrième Hokage, Minato Namikaze, réussit à sceller ce démon dans le corps de Naruto.Malheureusement il y laissa la vie.<br><br>\r\n                                C\'est ainsi que douze ans plus tard, Naruto rêve de devenir le plus grand Hokage de Konoha afin que tous le reconnaissent à sa juste valeur. Mais la route pour devenir Hokage est très longue et Naruto sera confronté à un bon nombre d\'épreuves et devra affronter de nombreux ennemis pour atteindre son but !', 'MASASHI Kishimoto', 'https://www.youtube.com/embed/j2hiC9BmJlQ', 27, 220, '../image/naruto1.jpg', '../image/naruto2.png'),
(7, 'Love Hina', 14, 'Comédie, Romantique', '../image/love_hina.jpg', 'Keitaro, 19 ans, a échoué par deux fois au concours d’entrée de l’université de Tokyo, Tôdai.<br> Mis à la porte par ses parents, il espère que sa grand-mère, propriétaire d’un hôtel, acceptera de l’héberger.<br> Mais surprise, l’établissement est devenu un pensionnat pour jeunes filles… dont Keitarô devient vite l’homme à tout faire ! Parviendra-t-il enfin à intégrer l’université pour tenir la promesse qu’il a faite enfant ?', 'AKAMATSU Ken', 'https://www.youtube.com/embed/1joqtOgJb4k', 14, 25, '../image/love_hina1.jpg', '../image/love_hina2.jpg'),
(8, 'One Piece', 12, 'Action, Aventure, Comédie, Drame, Fantasy', '../image/one_piece.jpg', 'Il fut un temps où Gold Roger était le plus grand de tous les pirates, le \"Roi des Pirates\" était son surnom.<br> A sa mort, son trésor d\'une valeur inestimable connu sous le nom de \"One Piece\" fut caché quelque part sur \"Grand Line\". De nombreux pirates sont partis à la recherche de ce trésor mais tous sont morts avant même de l\'atteindre.<br> Monkey D. Luffy rêve de retrouver ce trésor légendaire et de devenir le nouveau \"Roi des Pirates\".<br> Après avoir mangé un fruit du démon, il possède un pouvoir lui permettant de réaliser son rêve. Il lui faut maintenant trouver un équipage pour partir à l\'aventure !', 'EIICHIRO Oda', 'https://www.youtube.com/embed/bv7BoRBeKuU', 93, 892, '../image/one_piece1.jpg', '../image/one_piece2.jpg'),
(9, 'Yu Gi Oh', 8, 'Aventure, Jeu', '../image/yugioh.jpg', 'La légende dit que l\'énigmatique puzzle du Millennium réalisera un vœu à celui qui déchiffrera ses secrets antiques. Après avoir résolu le problème, le lycéen Yuugi Mutô relâche \"un autre Yuugi\", une présence particulière contenue à l\'intérieur du fameux puzzle. Maintenant, chaque fois qu’il est confronté à un dilemme, ce mystérieux alter ego fait son apparition et l’aide dans ses problèmes.\r\n\r\n                                Désireux de percer le mystère qui se cache derrière cet esprit étrange, Yuugi et ses compagnons se retrouvent en concurrence avec plusieurs adversaires dans \"Duel Monsters\", un jeu de cartes difficile utilisé par des personnes cherchant à voler le casse-tête du millénaire dans une tentative désespérée d\'exploiter la grande puissance en son sein. Au fur et à mesure que les questions se bousculent, ils se rendent vite compte qu’il n’ya pas que la fierté en jeu dans ces duels.', 'TAKAHASHI Kazuki', 'https://www.youtube.com/embed/ErhzuwW9uGs', 38, 224, '../image/yugioh1.jpg', '../image/yugioh2.jpg'),
(10, 'Dragon Ball', 12, 'Action, Aventure, Combat, Fantasy, Science-fiction', '../image/dragon_ball.png', 'Les mois ont passé depuis le terrible affrontement entre Goku et Majin Boo… Mais après une période de paix, une nouvelle menace s’abat encore sur la Terre !! Et cette fois, les ennemis viennent de “l’univers 6”… Qu’est-ce que ça signifie ?! Voici enfin la suite tant attendue et totalement inédite de Dragon Ball, sur une idée originale d’Akira Toriyama lui-même !!', 'AKIRA Toriyama', 'https://www.youtube.com/embed/rO3_O_5BYw4', 8, 131, '../image/dragon_ball1.jpg', '../image/dragon_ball2.jpg'),
(11, 'Full Metal Alchimist', 12, 'Aventure, Action, Science-fantasy, Steampunk, Surnaturel', '../image/full_metal_alchimist.jpg', 'Après avoir perdu leur mère, Edward et Alphonse tentent de la ramener à la vie grâce à l\'alchimie. Cependant, l\'alchimie doit obéir à la loi de l\'échange équivalent : l\'objet transformé et l\'objet issu de la transformation doivent être de masses équivalentes. Passer outre cette règle coûte très cher, et les frères Elric en feront les frais : Edward perd un bras et une jambe alors que son frère Alphonse perd son corps. Heureusement Edward réussit à enfermer l\'âme de son frère dans une armure de métal grâce à un sceau de sang.\r\n                                Ils décident alors de quitter leur maison pour partir à la recherche d\'informations sur la pierre philosophale, qui leur permettrait de regagner leurs corps. Cependant, ils ne sont pas les seuls à la recherche de cette pierre...', 'HIROMU Arakawa', 'https://www.youtube.com/embed/pvs8yiNUayU', 27, 51, '../image/full_metal_alchimist1.png', '../image/full_metal_alchimist2.jpg'),
(12, 'Assassination Classroom', 12, 'Action, Comédie, School Life, Science-fiction', '../image/ass_classroom.png', 'L\'histoire se déroule au prestigieux collège Kunugigaoka. Koro-sensei est une étrange créature qui déclare avoir subitement détruit 70 % de la Lune. Il prévoit ensuite de détruire la Terre en mars prochain pour des raisons inconnues. Il se présente ensuite au gouvernement japonais et annonce vouloir devenir le professeur principal de la classe 3-E du collège Kunugigaoka pour pouvoir les former en tant qu\'assassins et éliminer une cible bien particulière : lui-même, leur propre enseignant.\r\n\r\n                                Les élèves de cette classe auront donc pour objectif d\'assassiner leur professeur afin de sauver la Terre, la récompense étant de 10 milliards de yens. Cependant un problème se pose : Koro-sensei se déplace à Mach 20, possède des tentacules à fonctions infinies et, de plus, c\'est un excellent professeur ! Le gouvernement va accepter pour pouvoir le garder à l’œil à condition que Koro-sensei ne fasse pas de mal aux élèves2 ; mais les élèves réussiront-ils leur mission avant la date impartie ? ', 'YUSEI Matsui', 'https://www.youtube.com/embed/pYmYhFgYd5w', 21, 47, '../image/ass_classroom1.jpg', '../image/ass_classroom2.png'),
(13, 'Mär', 10, 'Aventure, Fantasy, Comédie, Magie, Romance, Combat', '../image/mar.jpg', 'Ginta Toramizu, un collégien ordinaire qui passe son temps à rêver de mondes féeriques, voit un jour s’ouvrir devant lui une porte magique. Il l’emprunte et se retrouve dans une étrange contrée.<br><br> C’est le pays de ses songes, peuplé de loups-garous, de sorcières, et où les maîtres artisans fabriquent grâce à la magie des \"Ärms\", des artefacts porteurs de grands pouvoirs.<br> Par hasard, Ginta s’empare de Babbo, un Ärm vivant et doué de parole. C’est le début d’une longue quête…', 'NOBUYUKI Anzai', 'https://www.youtube.com/embed/-72GPxnQVr8', 15, 102, '../image/mar1.jpg', '../image/mar2.jpg'),
(14, 'Tokyo Ghoul', 14, 'Action, Drame, Horreur, Épouvante, Mystère, Psychologie', '../image/tokyo_ghoul.png', 'Tokyo est devenue une ville cruelle et impitoyable, un endroit où des créatures vicieuses appelées «goules» existent aux côtés des humains. Les habitants de cette grande métropole vivent dans la peur constante de ces sauvages sanguinaires et de leur soif de chair humaine.<br> Cependant, la plus grande menace que ces goules posent est leur capacité dangereuse à se faire passer pour des humains et de se fondre dans la société.\r\n                                L\'histoire suit Ken Kaneki, un étudiant universitaire timide qui est immédiatement attiré par Rize Kamishiro, une lectrice avide comme lui.\r\n                                Cependant, Rize n\'est pas exactement ce qu\'elle pretend être.<br> Durant un rendez-vous, elle manque de tuer Kaneki en lui dévoilant sa nature de goule.\r\n                                Il survit grâce aux organes de Rize, greffés à la place de ceux qu\'elle avait détruit en l\'attaquant. Le jeune homme est désormais un hybride, mi-humain, mi-goule et va vivre un véritable enfer.', 'SUI Ishida', 'https://www.youtube.com/embed/YTAH8UW7YUY', 14, 24, '../image/tokyo_ghoul1.jpg', '../image/tokyo_ghoul2.jpg'),
(15, 'Murcielago', 16, 'Action, Comédie, Drame, Ecchi', '../image/murcielago.jpg', 'La justice est parfois inutile pour éradiquer le mal.\r\n                                    Pour faire face à la gangrène criminelle grandissante, le pays fait appel à une tueuse à gages professionnelle en la relaxant temporairement de sa peine de mort. Son nom : Kuroko Kômori.\r\n                                    Avec à ses côtés pour effectuer sa surveillance, Hinako Tozakura, fanatique de véhicules en tout genre et également chargée de sa surveillance... Embarquez et suivez leurs aventures dévastatrices.', 'YOSHIMURA Kana', 'https://www.youtube.com/embed/zGIzd3qTigU', 4, 0, '../image/murcielago1.jpg', '../image/murcielago2.jpg'),
(16, 'Fairy Tail', 10, 'Action, Aventure, Comédie, Fantasy', '../image/fairy_tail.jpg', 'Lucy est une jeune magicienne qui désire par dessus tout entrer dans une guilde magique.\r\n                                Elle décide de se rendre à Harujion afin d\'obtenir des infos sur les guildes, particulièrement la guilde Fairy Tail.\r\n                                Lors de ses recherches, elle rencontre le mystérieux Salamander, membre de la célèbre guilde Fairy Tail.\r\n                                Malheureusement ce dernier n\'est qu\'un charlatan qui utilise des enchantements pour envoûter des femmes et ainsi les revendre au marché d\'esclaves !\r\n                                Alors que Lucy se trouve sous l\'envoûtement de Salamander, un garçon mystérieux du nom de Natsu accompagné d\'un chat bleu pouvant parler appelé Happy, la percute et rompt le sortilège de Salamander. Pour remercier Natsu et Happy, elle décide de les inviter au restaurant. Plus tard, Salamander lui fait une proposition : si elle vient à la fête sur le bateau, qu\'il organise, il la fera entrer chez Fairy Tail. Lucy accepte et s\'y rend. A la fête, elle se rend compte que Salamander n\'est qu\'un escroc et qu\'il ne fait même pas partie de Fairy Tail. Elle veut fuir mais, alors qu\'elle est sur le point de se faire kidnapper, Natsu et Happy arrivent et la sauvent. C\'est alors qu\'elle découvre qu\'ils sont des mages et qu\'ils font partie de Fairy Tail.\r\n                                C\'est le début des aventures de Natsu et Lucy au sein du monde magique de Fairy Tail !', 'HIRO Mashima', 'https://www.youtube.com/embed/l1foxu5hBII', 63, 310, '../image/fairy_tail1.jpg', '../image/fairy_tail2.jpeg'),
(17, 'Platinum End ', 16, 'Drame, Mature, Mystère, Psychologique, School Life, Surnaturel, Tragique', '../image/platinum_end.jpg', 'Dieu se meurt. Selon la tradition, 13 Anges sont envoyés au Japon et doivent choisir chacun un humain qui recevra le pouvoir de vie et de mort sur les autres hommes pendant 999 jours. Au terme de ce délai, les actions des candidats au poste de Dieu seront jugées et l\'un d\'eux sera élu pour être le nouveau Dieu du Paradis.<br><br>\r\n                                Mirai Kakehashi est un lycéen qui n\'espère plus rien de la vie ; ayant perdu ses parents très jeune et étant battu par son oncle et sa tante, la seule famille qui lui reste, il choisit de se suicider en sautant du toit d\'un immeuble. Mais il est sauvé de justesse par Nasse, une Ange qui lui offre trois pouvoirs spéciaux et fait de lui l\'un des 13 candidats au poste de Dieu.<br><br>\r\n                                Dorénavant, Mirai a la capacité de changer les gens qui l\'entourent. Mais parviendra t-il à reprendre goût à la vie grâce à ces dons du ciel ?', 'OHBA Tsugumi', 'https://www.youtube.com/embed/tryG0xEcdgU', 10, 0, '../image/platinum_end1.jpg', '../image/platinum_end2.png'),
(18, 'Negima', 12, 'Action, Comédie, Romance, Magie', '../image/negima.jpg', 'Negi Springfield, dix ans, vient de terminer sept ans d\'études de magie. Afin de devenir magicien accompli, il est envoyé au Japon pour être professeur d\'anglais dans une classe du collège Mahora.\r\n                                À son arrivée sur le campus, il a un accrochage avec Asuna Kagurazaka,une de ses élèves, chez qui par décision du proviseur il va loger temporairement, et qui par-dessus tout découvre rapidement qu\'il est magicien.\r\n                                Il va également découvrir qu\'être professeur d\'une classe de filles n\'est pas de tout repos...', 'AKAMATSU Ken', 'https://www.youtube.com/embed/R91AiG8SbNA', 38, 26, '../image/negima1.jpg', '../image/negima2.jpg'),
(19, 'Mirumo', 8, 'Comédie, Magie, Romance, Fiction, Fantasy', '../image/mirmo.jpg', 'Kaede (camille), est secrètement amoureuse de son camarade de classe, mais perd tous ces moyens dés qu\'elle s\'approche de lui. Un jour en lisant un message inscrit dans une tasse de thé, elle fait le voeu de sortir avec Yuki, c\'est alors que surgit Mirumo, prince du royaume des Muglins qui va l\'aider à ce que son voeux se réalise. Mais l\'espiègle petit personnage va rapidement perturber le quotidien de Kaede...', 'HIROMU Shinozuka', 'https://www.youtube.com/embed/SpU-Y5Nu_lw', 12, 172, '../image/mirumo1.jpg', '../image/mirumo2.png'),
(20, 'Zatch Bell', 12, 'Action, Aventure, Comédie, Fantastique, Combat ', '../image/zatch_bell.jpg', 'Zatch est un petit démon venue du Royaume des Démons avec un livre, remplis de ses sortilèges. Il doit faire équipe avec un humain afin de gagner le \"tournoi\" auquel il participe, mais Zatch a perdu la mémoire suite à un mauvais atterrissage dans le monde des humains et est recueilli par le professeur Takamine qui, plus tard, l\'enverra à son fils : Kiyomaro.\r\n                                Kiyomaro est un jeune homme intelligent et cultivé, mais qui se désintéresse totalement du système scolaire, et préfère paressé. Son père espère que Zatch pourra le sortir de cet état.\r\n                                En effet, lorsqu\'il rencontre le petit démon, Kiyomaro se rend vite compte qu\'il peut lire les formules du livre de sort, et ainsi, aidé Zatch dont la raison de la présence sur Terre est le fameux \"tournoi des Démons\". Cent petits démons sont envoyés sur Terre et se battent jusqu\'à ce que leur livre soit détruit. Une fois que c\'est le cas, ils retournent dans leur monde. Le dernier démon resté sur Terre sera le prochain Roi.', 'RAIKU Makoto', 'https://www.youtube.com/embed/rYg36rJKumc', 33, 150, '../image/zatch_bell1.jpg', '../image/zatch_bell2.jpeg'),
(21, 'L\' Attaque des Titans', 14, 'Action, Drame, Fantastique, Horreur, Mature, Mystère, Surnaturel, Tragique', '../image/attaque_des_titans.png', 'Eren est un petit garçon rêvant de voyager dans le monde extérieur. Mais cela est impossible car il vit dans une ville fortifiée aux murailles dépassant les cinquante mètres de haut. Ces remparts sont nécessaires à la sécurité des habitants car ils sont les derniers représentants de l’humanité, obligés de se cacher pour échapper aux titans qui ont massacré la majeure partie du genre humain un siècle plus tôt. Eren est têtu : il ne se doute pas de la violence des combats qui ont opposé les hommes aux titans. Il décide de poster sa candidature pour devenir éclaireur, car il s\'agit des seuls soldats autorisés à sortir de la ville pour en savoir plus sur les titans. Mais un beau jour, un géant parvient à détruire le mur qui protégeait la ville et ouvre la voie à plusieurs dizaines de ses congénères ! Eren assiste impuissant à la mort atroce de sa mère qui finit dévorée. Alors qu’il fuit avec d’autres survivants, il se jure de se venger et de détruire la race des titans jusqu’à ce qu’il n’en reste plus un seul !!', 'ISAYAMA Hajime', 'https://www.youtube.com/embed/Zfgjgs4EKHU', 28, 58, '../image/attack_des_titans1.jpg', '../image/attaque_des_titans2.jpg'),
(22, 'UQ Holder', 14, 'Combats, Harem, Magie, Vampires, Voyage temporel ', '../image/uq_holder.jpg', 'Cela fait désormais 10 ans que le monde est au courant de l\'existence de la magie et de grands changements se sont opérés depuis. Tôta est un jeune garçon qui vit à la campagne, éloigné de toute magie, sous la responsabilité de Yukihime, un professeur sachant utiliser cette fameuse \"magie\". Accompagné de ses amis, Tôta essaye de battre la fameuse jeune femme car, qui arrive à la battre, pourra rejoindre la capitale ! C\'est lors d\'une nouvelle bataille pour la vaincre que la vie du jeune garçon se retrouve bouleversée, bien plus qu\'il ne l\'aurait imaginé.', 'AKAMATSU Ken', 'https://www.youtube.com/embed/VFLPphQAm-M', 18, 12, '../image/uq_holder1.jpg', '../image/uq_holder2.jpg'),
(23, 'City Hunter', 14, 'Action, Comédie, Roman noir, Policier', '../image/city_hunter.jpg', 'Ryo Saeba, surnommé \"City Hunter\" est un \"nettoyeur\", sur contrat, il débarrasse Tokyo qui regorge de criminels en tout genre. Tireur d\'élite hors pair, il le plus souvent engagé comme garde du corps. Avec sa partenaire Kaori, avec laquelle il entretient une relation atypique, ils forment un duo d\'enfer que rien ne peut arrêter...', 'TSUKASA Hōjō', 'https://www.youtube.com/embed/UvIh1_8Fvrc', 35, 140, '../image/city_hunter1.jpg', '../image/city_hunter2.jpg'),
(24, 'The Promised Neverland ', 14, 'Aventure, Dark fantasy, Drame, Science-fiction, Surnaturel, Thriller ', '../image/the_promised_neverland.jpg', 'Emma et ses amis, tous orphelins, ont été placés dans un établissement spécialisé lorsqu\'ils étaient tout jeune. Bien que leur liberté soit limitée et que les règles soient parfois un peu strictes, ils mènent une vie agréable tous ensemble et la femme qui s\'occupe d\'eux est généreuse. Cependant, une question anime Emma et tous les autres : pourquoi n\'ont-ils pas le droit de sortir de l\'orphelinat ?', 'KAIU Shirai ', 'https://www.youtube.com/embed/828OYMaPlMA', 8, 12, '../image/the_promised_neverland1.jpg', '../image/the_promised_neverland2.jpg'),
(25, 'Danganronpa ', 14, 'Action, Horreur, Épouvante, Mystère, Psychologique, Thriller', '../image/danganronpa.jpg', 'L’Académie du Pic de l’Espoir est un établissement réputé pour son processus de sélection extrêmement strict : seuls les lycéens qui excellent dans leur domaine peuvent y entrer. Lorsque Makoto est tiré au sort pour l’intégrer, il est donc aux anges... C’est pourtant sa descente aux enfers qui commence lorsqu’il se retrouve prisonnier d’un jeu de la mort avec ses camarades. Et il devra garder la tête froide face au diabolique proviseur Monokuma... ', 'KODAKA Kazutaka', 'https://www.youtube.com/embed/266zEWMYHds', 4, 13, '../image/danganronpa1.jpg', '../image/danganronpa2.jpg'),
(26, 'Elfen Lied', 16, 'Action, Drame, Ecchi, Fantasy, Horreur, Épouvante, Psychologique, Romance, Science-fiction', '../image/elfen_lied.png', 'Lucy est une Diclonius dite très dangereuse. Elle est enfermée dans un laboratoire mais elle réussit à s\'en échapper en tuant tous ses opposants grâce à ses vecteurs: des bras invisibles. Lucy a voulu grandir comme tous les enfants, mais à cause de ses cornes, les autres la traitaient différement, comme un monstre. A cause d\'eux, Lucy a commencé à commettre des meurtres, et s\'est finalement retrouvée enfermée. En s\'échappant du laboratoire, elle va se prendre une balle dans la tête et va perdre la mémoire. Elle sera retrouvée par Kouta qui la prénommera \"Nyu\". Cela dit, elle retrouvera sa lucidité à certains moments, surtout quand sa vie sera en danger et n\'hésitera pas à tuer tous ceux qui la menacent.', 'OKAMOTO Lynn', 'https://www.youtube.com/embed/YgBTBIUVW0M', 12, 13, '../image/elfen_lied1.jpg', '../image/elfen_lied2.jpg'),
(27, 'Another', 16, 'Horreur, Épouvante, Mystère, Psychologique, School Life, Surnaturel', '../image/another.jpeg', 'En 1972, dans l\'établissement de Yomiyama au Japon, une jeune nommée Yomiyama Misaki meurt dans un accident mystérieux. Ses camarades de la classe 3-3, très attristés et ne voulant pas y croire, décident de faire comme si elle était encore en vie jusqu\'à la fin de l\'année, lors de la remise des diplômes. C\'est alors le début d\'une longue histoire...\r\n\r\nVingt-six ans après le drame, en 1998, un jeune garçon nommé Koichi Sakakibara est transféré dans la classe 3-3.\r\nIl fait alors la connaissance d\'une élève très discrète et mystérieuse, Misaki Mei qui porte un étrange bandeau à son œil gauche à laquelle aucun autre élève ne semble parler ou prêter attention.\r\nDans cette classe, il y découvre une atmosphère tendue ainsi qu\'un étrange comportement provenant de ses nouveaux camarades de classe qui semblent cacher un secret terrible et inavouable...', 'AYATSUJI Yukito ', 'https://www.youtube.com/embed/1cmo4c5-QLs', 4, 12, '../image/another1.jpg', '../image/another2.jpg'),
(28, 'Steins Gate', 14, 'Comédie, Drame, Mystère, Psychologique, Romance, Science-fiction, Thriller', '../image/stein_gate.png', 'L\'histoire de Steins;Gate se déroule dans le quartier otaku d\'Akihabara, et porte sur un groupe d\'amis qui ont transformé leur micro-ondes par inadvertance en dispositif pouvant envoyer des messages texte vers le passé. Dans le but de comprendre ce phénomène ils effectuent différentes expériences concernant le voyage dans le temps. Ils sont vite traqués par le centre de recherche CERN (ou SERN), qui réalise ses propres recherches sur les voyages temporels. Rintaro va donc utiliser la capacité du four à micro-ondes et se rendre rapidement compte que chaque modification du passé a un impact irréversible sur le présent, à cause de la théorie des mondes multiples', 'KENJI Mizuta', 'https://www.youtube.com/embed/6nB_bEM1oFk', 3, 25, '../image/stein_gate1.jpg', '../image/stein_gate2.jpg'),
(29, 'Black Butler', 14, 'Anges, Démons, Détective, Gore, Histoire, Shinigami, Vengeance', '../image/black_butler.jpg', 'Lorsqu\'on le regarde au début, ce manoir perdu dans la campagne de Londres parait tout à fait normal.\r\nMais ce manoir est habité par des personnes pour le moins étranges : Ciel Phantomhive (Funtomhive) jeune maître de 12 ans, industriel hors-pair à la tête de la famille la plus redoutée de l\'Angleterre ; un majordome démoniaque, Sebastian Michaelis, doué pour les tâches ménagères comme pour les arts-martiaux ; un maître d\'hôtel, Tanaka, qui ne sait rien faire d\'autre que boire du saké et dire \"oh oh oh\" ; un cuisinier aux plats douteux, Bard, ne sachant cuisiner sa viande qu\'au lance-flammes ; une servante, May Lin, tellement maladroite qu\'elle pourrait vous tuer sans le vouloir ; et un jardinier, Finnian, à la force surhumaine, qui se croit à démolition land qui ne sait donc entretenir un jardin qu\'en le dévastant.\r\nEt lorsque tout ce petit monde a affaire à des personnages aussi peu recommandable que Jack L\'éventreur, forcément, ça fait tâche...', 'TOBOSO Yana', 'https://www.youtube.com/embed/OW-ZdPyj7x0', 28, 53, '../image/black_butler1.jpg', '../image/black_butler2.jpg'),
(30, 'Naruto Shippuden', 10, 'Action, Aventure, Comédie, Drame, Fantasy, Combat', '../image/naruto_shippuden.jpg', 'L\'histoire de Naruto Shippuden se déroule deux ans et demie après le départ de Naruto à Konoha. On y retrouve tous les personnages plus mûrs et plus âgés.\r\n\r\nL\'intrigue tourne autour des aventures de Naruto et Sakura à la recherche de Sasuke, parti de Konoha pour acquérir de nouveaux pouvoirs, mais on y découvre aussi les objectifs de l\'Akatsuki.', 'KISHIMOTO Masashi', 'https://www.youtube.com/embed/thh7bVCgDHs', 45, 500, '../image/naruto_shippuden1.jpeg', '../image/naruto_shippuden2.jpg'),
(31, 'Fairy Gone', 14, 'Action, Aventure, Fantasy, Surnaturel', '../image/fairy_gone.jpg', 'L\'histoire se déroule dans un monde où les fées existent et résident dans des corps d\'animaux, leur conférant de puissants pouvoirs. En prélevant l\'organe d\'un animal possédé et en l\'implantant dans le corps d\'un humain, il est possible d\'attribuer ces mêmes capacités surnaturelles aux hommes. Les humains qui ont eu droit à une transplantation sont ainsi utilisés sur les champs de bataille et appelés « soldats féeriques », en raison de leur lien avec les fées qui les habite partiellement.\r\n\r\nAprès avoir connu une grande période de trouble, les « soldats féeriques » ont aujourd\'hui dû réintégrer la société, la paix ayant été rétablie dans le monde.\r\n\r\nNeuf ans après la grande guerre, on suit les aventures de Maria Noel, nouvelle recrue au sein de l\'organisation secrète \"Dorothea\", dédiée à la recherche et à la répression des crimes et incidents liés aux fées.', 'KENICHI Suzuki', 'https://www.youtube.com/embed/e_-qiAsZUcc', 1, 24, '../image/fairy_gone1.jpg', '../image/fairy_gone2.jpg'),
(32, 'Dororo', 16, 'Action, Aventure, Fantastique, Historique, Surnaturel', '../image/dororo.jpg', 'Hyakkimaru est infirme : 48 parties de son corps ont été vendues à autant de démons avant sa naissance. Rafistolé par un chirurgien compatissant, adolescent, il se découvre d\'étranges pouvoirs psychiques. Accompagné de Dororo, un petit voleur espiègle, il arpente le Japon à la recherche d\'un endroit où vivre en paix… affrontant au passage esprits et forces obscures.', 'OSAMU Tezuka', 'https://www.youtube.com/embed/DLat_-OyHIs', 4, 24, '../image/dororo1.jpg', '../image/dororo2.jpg'),
(33, 'Shimoneta to Iu Gainen', 16, 'Comédie, Ecchi, School Life', '../image/shimoneta.jpg', 'L\'histoire se passe 16 années après l\'application de la « Loi au maintien à l\'ordre public et de la morale pour le développement de la Jeunesse » qui interdit le langage grossier ou les situations jugées indécentes en public dans le pays. Nous suivons Tanukichi Okuma qui s\'inscrit dans une école d\'élite de bonnes mœurs mais qui est enrôlé par l\'Organisation Anti-Système (SOX). Tanukichi va prendre part aux actes obscènes contre l\'école.', 'HIROTAKA Akagi', 'https://www.youtube.com/embed/K2Xe7ei1WkY', 11, 12, '../image/shimoneta1.jpg', '../image/shimoneta2.jpg'),
(34, 'Hamatora', 12, 'Action, Comédie, Drame, Fantasy, Mystère, Surnaturel', '../image/hamatora.jpeg', 'L\'équipe de détectives Hamatora est composé de deux utilisateurs de ce pouvoir : Nice et Murasaki.\r\nUn jour, alors qu\'ils travaillaient à Yokohama, ils tombent sur des infos concernant un dangereux serial killer recherché par un de leurs amis.\r\nMais rapidement, il s\'avère que ce tueur ne s\'attaque qu\'aux gens comme eux, qui sont nés avec un pouvoir.', 'YUKINO Kitajima', 'https://www.youtube.com/embed/Slnzv-4_oVI', 3, 12, '../image/hamatora1.jpeg', '../image/hamatora2.jpg'),
(35, 'Netoge no Yome', 14, 'Comédie, Ecchi, Romance, School Life', '../image/netoge.png', 'Hideki Nishimura a avoué ses sentiments à une fille sur un jeu en ligne, cependant cette fille s\'est révélée être une homme dans la vie réelle. Ce dernier décide de garder cette sombre partie de sa vie pour le passé et de ne plus jamais faire confiance aux \"femmes\" sur les jeux en ligne.\r\n\r\nCependant, un jour une fille en ligne lui avoue être amoureuse de lui et cette fois-ci il s\'agit bel et bien d\'une lycéenne nommée Ako Tamaki.\r\n\r\nAko ne peut pas faire la différence entre le monde en ligne et la réalité et possède de grosses difficultés à communiquer avec les autres dans la vie réelle. Hideki et ses amis de la guilde décident de la guérir dans le monde réel et de la faire réagir.', 'SHIBAI Kineko', 'https://www.youtube.com/embed/JTFQaCC9KmY', 3, 12, '../image/netoge1.jpg', '../image/netoge2.jpg'),
(36, 'Charlotte', 10, 'Action, Comédie, Drame, Romance', '../image/charlotte.jpg', 'L\'histoire nous entraîne dans un monde où certains enfants, durant la puberté, développent des pouvoirs spéciaux. Ces enfants sont nommés ESPers. Yuu Otosaka, l\'un d\'eux, semble être en apparence un simple lycéen. Cependant ce dernier à la capacité de pouvoir se glisser et de contrôler entièrement le corps d\'une personne, mais seulement durant cinq secondes. Yuu a utilisé cette compétence durant des années pour atteindre ses objectifs, ce qui lui a permis de pouvoir rentrer dans un lycée prestigieux.\r\n\r\nUn jour, il est pris la main dans le sac par l\'énigmatique, Nao Tomori. Ne pouvant plus reculer, lui et sa sœur Ayumi sont contraints d\'être transférés à l\'Académie Hoshi-no-umi, un établissement pour des étudiants aux capacités surnaturelles.\r\n\r\nLe Bureau des Élèves (BDE) de cette école, mené par la fameuse Nao, est chargé de traquer les adolescents abusant de leurs pouvoirs. Ainsi, Yuu se retrouve obligé de rejoindre le BDE, qui jours après jours, va le mener sur la vérité qui attend tous les détenteurs de ces capacités surnaturelles : les ESPers...', 'JUN Maeda', 'https://www.youtube.com/embed/hfmRxXVvFYA', 1, 13, '../image/charlotte1.png', '../image/charlotte2.jpg'),
(37, 'Ulysses : Jeanne d\'Arc', 12, ' Action - Fantastique - Fantasy - Romance', '../image/ulysse.jpg', 'Au XVème siècle, la Guerre de 100 ans fait rage et oppose la France à l\'Angleterre. Fils d\'un noble, Montmorency profite de ses études dans une école de chevalier pour étudier la magie et l\'alchimie. Seulement, alors que la France perd la guerre, l\'école est dissoute et Montmorency est contraint de fuir. Dans son évasion, il rencontre une miraculée d\'Azincourt, prise par les anglais : Jeanne.', 'MIKAGE Kasuga', 'https://www.youtube.com/embed/SKABCEOW0OI', 7, 12, '../image/ulysse1.jpg', '../image/ulysse2.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `Fan_Art`
--
ALTER TABLE `Fan_Art`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `manga`
--
ALTER TABLE `manga`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `Fan_Art`
--
ALTER TABLE `Fan_Art`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `manga`
--
ALTER TABLE `manga`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=348;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
